services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydb'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
    ports:
      - '3307:3306'

  redis:
    image: 'redis:latest'
    container_name: redis-server
    ports:
      - '6379:6379'
