spring:
  application:
    name: bookjourney
  profiles:
    group:
      local: db-local, port-local, common
      prod: db-prod, port-prod, common
    active: local

---
#로컬용 DB
spring:
  config:
    activate:
      on-profile: local
  #
  #  datasource:
  #    url: jdbc:mysql://localhost:3306/book_journey
  #    username: ${LOCAL_DB_USER}
  #    password: ${LOCAL_DB_PASSWORD}
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #
  #  jpa:
  #    hibernate:
  #      ddl-auto: update
  #    show-sql: true
  #    properties:
  #      hibernate:
  #        format_sql: true
  #        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:h2:mem:BookJourneyBackendApplication;MODE=MYSQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  docker:
    compose:
      enabled: false  # local 환경에서 Docker Compose 비활성화

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 604800000 #7일
  refresh-token-expiration: 1209600000 # 14일 (14 * 24 * 60 * 60 * 1000)
#jwt:
#  secret: ${JWT_SECRET} #토큰 테스트용
#  access-token-expiration: 25000 #25초
#  refresh-token-expiration: 60000 #1분

---
#배포용 DB
spring:
  config:
    activate:
      on-profile: prod
#  datasource:
#    url: jdbc:mysql://:3306/book_journey
#    username: ${PROD_DB_USER}
#    password: ${PROD_DB_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    url: jdbc:mysql://my-db:3306/mydb
    username: root
    password: verysecret
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: my-cache-server
      port: 6379

  docker:
    compose:
      enabled: true  # prod 환경에서 Docker Compose 활성화

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 604800000 #7일
  refresh-token-expiration: 1209600000 # 14일 (14 * 24 * 60 * 60 * 1000)


---
#배포용 포트
spring:
  config:
    activate:
      on-profile: port-prod

server:
  port: 8080
  servlet:
    context-path: /

---
#로컬용 포트
spring:
  config:
    activate:
      on-profile: port-local

server:
  port: 8080
  servlet:
    context-path: /

---
#공통
spring:
  config:
    activate:
      on-profile: common

  mail:
    host: smtp.gmail.com
    port: 587
    username: bookjourney.server@gmail.com
    password: ${EMAIL_SECRET}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000 #5초
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-minutes: 720  #12시간
    auth-code-request-expiration-minutes: 1440  #24시간

aladin:
  key: ${ALADIN_API_KEY}

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: eu-north-1
      auto: false
    stack:
      auto: false
